"""
Configuration des étapes de transaction immobilière (parcours acheteur et vendeur)
Basé sur le parcours québécois documenté
"""

# Étapes acheteur
BUYER_STEPS: list[dict] = [
    {
        "code": "preparation",
        "title": "Préparation et recherche",
        "description": "Définir vos besoins, obtenir une préapprobation hypothécaire et choisir un courtier",
        "order": 1,
        "view": "acheteur",
        "actions": [
            {
                "code": "a1",
                "title": "Définir budget et besoins",
                "description": "Établir les critères de recherche et évaluer la capacité financière",
                "required": True,
                "documents": [],
                "lea_guidance": "Je peux vous aider à calculer votre budget maximal en tenant compte de vos revenus, dettes et mise de fonds disponible.",
            },
            {
                "code": "a2",
                "title": "Obtenir préapprobation hypothécaire",
                "description": "Démarcher une institution financière pour connaître sa capacité d'emprunt",
                "required": True,
                "documents": ["Preuve de revenus", "Relevés bancaires"],
                "lea_guidance": "Une préapprobation hypothécaire renforce votre position lors des négociations. Je peux vous guider sur les documents à préparer.",
            },
            {
                "code": "a3",
                "title": "Signer contrat de courtage",
                "description": "Choisir un courtier immobilier et signer le contrat de courtage exclusif",
                "required": True,
                "documents": ["Contrat de courtage – Achat"],
                "lea_guidance": "Le contrat de courtage vous protège et définit clairement les services que votre courtier vous fournira.",
            },
        ],
    },
    {
        "code": "submit_offer",
        "title": "Promesse d'achat",
        "description": "Rédiger et soumettre une offre formelle sur la propriété",
        "order": 2,
        "view": "acheteur",
        "actions": [
            {
                "code": "a4",
                "title": "Rédiger la promesse d'achat",
                "description": "Le courtier rédige l'offre sur le formulaire obligatoire OACIQ",
                "required": True,
                "documents": ["Formulaire Promesse d'achat"],
                "lea_guidance": "La promesse d'achat doit inclure le prix offert, les conditions suspensives (inspection, financement) et les délais.",
            },
            {
                "code": "a5",
                "title": "Négocier les termes",
                "description": "Le vendeur peut accepter, refuser ou faire une contre-proposition",
                "required": True,
                "documents": [],
                "lea_guidance": "Les négociations peuvent impliquer plusieurs contre-propositions. Je peux vous conseiller sur les stratégies de négociation.",
            },
        ],
    },
    {
        "code": "accept_offer",
        "title": "Offre acceptée",
        "description": "L'offre est acceptée, réaliser les conditions suspensives",
        "order": 3,
        "view": "acheteur",
        "actions": [
            {
                "code": "a6",
                "title": "Planifier l'inspection préachat",
                "description": "Engager un inspecteur en bâtiment certifié",
                "required": True,
                "documents": ["Rapport d'inspection"],
                "lea_guidance": "L'inspection doit être faite dans les 10 jours. Je peux vous recommander des inspecteurs certifiés dans votre région.",
                "due_date_field": "inspection_deadline",
            },
            {
                "code": "a7",
                "title": "Finaliser le financement",
                "description": "Fournir tous les documents à la banque pour l'approbation finale",
                "required": True,
                "documents": ["Promesse d'achat acceptée", "Rapport d'inspection"],
                "lea_guidance": "Assurez-vous d'avoir tous les documents requis : preuve d'emploi récente, relevés bancaires, déclarations de revenus.",
                "due_date_field": "financing_deadline",
            },
            {
                "code": "a8",
                "title": "Souscrire assurance habitation",
                "description": "Obtenir une preuve d'assurance habitation",
                "required": True,
                "documents": ["Preuve d'assurance"],
                "lea_guidance": "L'assurance habitation est obligatoire pour obtenir le prêt hypothécaire. Comparez plusieurs assureurs pour le meilleur prix.",
            },
        ],
    },
    {
        "code": "complete_inspection",
        "title": "Inspection complétée",
        "description": "Inspection effectuée et rapport reçu",
        "order": 4,
        "view": "acheteur",
        "actions": [
            {
                "code": "a9",
                "title": "Analyser le rapport d'inspection",
                "description": "Examiner les problèmes identifiés avec votre courtier",
                "required": True,
                "documents": [],
                "lea_guidance": "Je peux vous aider à comprendre les enjeux du rapport et à évaluer si des négociations sont nécessaires.",
            },
            {
                "code": "a10",
                "title": "Négocier réparations ou ajustement de prix",
                "description": "Si des problèmes majeurs sont découverts",
                "required": False,
                "documents": [],
                "lea_guidance": "Selon la gravité des problèmes, vous pouvez demander une réduction de prix, des réparations ou vous retirer de la transaction.",
            },
        ],
    },
    {
        "code": "approve_financing",
        "title": "Financement approuvé",
        "description": "Approbation hypothécaire confirmée par la banque",
        "order": 5,
        "view": "acheteur",
        "actions": [
            {
                "code": "a11",
                "title": "Recevoir lettre d'engagement",
                "description": "Obtenir la confirmation écrite de la banque",
                "required": True,
                "documents": ["Lettre d'engagement hypothécaire"],
                "lea_guidance": "La lettre d'engagement confirme que la banque s'engage à vous prêter le montant nécessaire.",
            },
            {
                "code": "a12",
                "title": "Choisir un notaire",
                "description": "Sélectionner le notaire qui rédigera l'acte de vente",
                "required": True,
                "documents": [],
                "lea_guidance": "Le notaire est choisi par l'acheteur. Je peux vous expliquer son rôle et vous suggérer des questions à lui poser.",
            },
        ],
    },
    {
        "code": "complete_signing",
        "title": "Signature chez le notaire",
        "description": "Signature de l'acte de vente officialisant le transfert",
        "order": 6,
        "view": "acheteur",
        "actions": [
            {
                "code": "a13",
                "title": "Préparer les fonds requis",
                "description": "Chèque certifié ou virement pour la mise de fonds et les frais",
                "required": True,
                "documents": [],
                "lea_guidance": "Vous devrez payer la mise de fonds, les droits de mutation, les honoraires du notaire et autres frais de clôture.",
            },
            {
                "code": "a14",
                "title": "Signer l'acte de vente",
                "description": "Signature officielle chez le notaire",
                "required": True,
                "documents": ["Acte de vente", "Acte de prêt hypothécaire"],
                "lea_guidance": "Le notaire vous expliquera tous les documents avant la signature. N'hésitez pas à poser des questions.",
            },
        ],
    },
    {
        "code": "transfer_keys",
        "title": "Prise de possession",
        "description": "Remise des clés et prise de possession de la propriété",
        "order": 7,
        "view": "acheteur",
        "actions": [
            {
                "code": "a15",
                "title": "Récupérer les clés",
                "description": "Obtenir toutes les clés et codes d'accès",
                "required": True,
                "documents": [],
                "lea_guidance": "Faites une inspection finale de la propriété avant de prendre possession pour vous assurer que tout est conforme.",
            },
            {
                "code": "a16",
                "title": "Effectuer l'inspection finale",
                "description": "Vérifier que la propriété est dans l'état convenu",
                "required": True,
                "documents": [],
                "lea_guidance": "Vérifiez que les inclusions sont présentes et que les réparations convenues ont été effectuées.",
            },
        ],
    },
]

# Étapes vendeur
VENDOR_STEPS: list[dict] = [
    {
        "code": "preparation",
        "title": "Préparation et mise en marché",
        "description": "Choisir un courtier, établir le prix et préparer la propriété",
        "order": 1,
        "view": "vendeur",
        "actions": [
            {
                "code": "v1",
                "title": "Signer contrat de courtage",
                "description": "Choisir un courtier et signer le contrat de courtage exclusif – Vente",
                "required": True,
                "documents": ["Contrat de courtage – Vente"],
                "lea_guidance": "Le contrat établit le prix de vente, la commission du courtier et les activités promotionnelles.",
            },
            {
                "code": "v2",
                "title": "Remplir déclarations du vendeur",
                "description": "Fournir toutes les informations connues sur l'état de la propriété",
                "required": True,
                "documents": ["Formulaire Déclarations du vendeur sur l'immeuble"],
                "lea_guidance": "Ce formulaire vous protège contre les poursuites futures. Soyez transparent sur tous les aspects de la propriété.",
            },
            {
                "code": "v3",
                "title": "Préparer la propriété",
                "description": "Home staging, réparations mineures, photos professionnelles",
                "required": False,
                "documents": [],
                "lea_guidance": "Une propriété bien présentée se vend plus rapidement et à meilleur prix. Je peux vous donner des conseils de mise en valeur.",
            },
        ],
    },
    {
        "code": "publish_listing",
        "title": "Propriété listée",
        "description": "La propriété est publiée et visible sur les plateformes",
        "order": 2,
        "view": "vendeur",
        "actions": [
            {
                "code": "v4",
                "title": "Organiser les visites",
                "description": "Coordonner les visites avec le courtier",
                "required": True,
                "documents": [],
                "lea_guidance": "Gardez la propriété propre et accueillante. Abstenez-vous d'être présent lors des visites pour laisser les acheteurs à l'aise.",
            },
            {
                "code": "v5",
                "title": "Obtenir certificat de localisation",
                "description": "Commander un certificat de localisation à jour",
                "required": True,
                "documents": ["Certificat de localisation"],
                "lea_guidance": "Le certificat doit avoir moins de 10 ans et être conforme. Commandez-le dès maintenant pour éviter les délais.",
            },
        ],
    },
    {
        "code": "receive_offer",
        "title": "Réception d'offre",
        "description": "Une ou plusieurs promesses d'achat sont reçues",
        "order": 3,
        "view": "vendeur",
        "actions": [
            {
                "code": "v6",
                "title": "Analyser les offres",
                "description": "Examiner toutes les offres avec votre courtier",
                "required": True,
                "documents": [],
                "lea_guidance": "Ne considérez pas seulement le prix. Évaluez aussi les conditions, les délais et la solidité financière des acheteurs.",
            },
            {
                "code": "v7",
                "title": "Accepter ou contre-proposer",
                "description": "Décider d'accepter, refuser ou faire une contre-proposition",
                "required": True,
                "documents": ["Formulaire Contre-proposition"],
                "lea_guidance": "Une contre-proposition annule l'offre initiale. Assurez-vous d'être à l'aise avec vos modifications.",
            },
        ],
    },
    {
        "code": "accept_offer",
        "title": "Offre acceptée",
        "description": "L'offre est acceptée, l'acheteur doit réaliser ses conditions",
        "order": 4,
        "view": "vendeur",
        "actions": [
            {
                "code": "v8",
                "title": "Permettre l'inspection",
                "description": "Donner accès à la propriété pour l'inspection préachat",
                "required": True,
                "documents": [],
                "lea_guidance": "L'acheteur a généralement 10 jours pour faire inspecter. Assurez-vous que la propriété soit accessible.",
                "due_date_field": "inspection_deadline",
            },
            {
                "code": "v9",
                "title": "Préparer documents pour notaire",
                "description": "Rassembler tous les documents requis",
                "required": True,
                "documents": ["Certificat de localisation", "Comptes de taxes", "Quittance hypothécaire"],
                "lea_guidance": "Le notaire aura besoin de plusieurs documents. Commencez à les rassembler maintenant pour éviter les retards.",
            },
            {
                "code": "v10",
                "title": "Obtenir quittance hypothécaire",
                "description": "Demander la quittance à votre institution financière",
                "required": True,
                "documents": [],
                "lea_guidance": "La quittance peut prendre 2-3 semaines. Contactez votre banque dès maintenant.",
                "due_date_field": "financing_deadline",
            },
        ],
    },
    {
        "code": "complete_signing",
        "title": "Signature chez le notaire",
        "description": "Signature de l'acte de vente et transfert de propriété",
        "order": 5,
        "view": "vendeur",
        "actions": [
            {
                "code": "v11",
                "title": "Signer l'acte de vente",
                "description": "Signature officielle chez le notaire",
                "required": True,
                "documents": ["Acte de vente"],
                "lea_guidance": "Le notaire vous remettra le produit de la vente après avoir remboursé votre hypothèque et payé tous les frais.",
            },
            {
                "code": "v12",
                "title": "Recevoir le produit de la vente",
                "description": "Le notaire distribue les fonds",
                "required": True,
                "documents": [],
                "lea_guidance": "Vous recevrez le prix de vente moins l'hypothèque, la commission du courtier et les frais de clôture.",
            },
        ],
    },
    {
        "code": "transfer_keys",
        "title": "Remise des clés",
        "description": "Libérer la propriété et remettre les clés",
        "order": 6,
        "view": "vendeur",
        "actions": [
            {
                "code": "v13",
                "title": "Vider la propriété",
                "description": "Retirer tous vos biens et nettoyer",
                "required": True,
                "documents": [],
                "lea_guidance": "Assurez-vous de laisser les inclusions convenues et de retirer toutes les exclusions.",
            },
            {
                "code": "v14",
                "title": "Remettre toutes les clés",
                "description": "Fournir toutes les clés, codes et télécommandes",
                "required": True,
                "documents": [],
                "lea_guidance": "Préparez un inventaire complet : clés de portes, garage, cabanon, codes d'alarme, télécommandes, etc.",
            },
        ],
    },
]
